### ISSUE TITLE
Cargo Release

### ISSUE THREAD

**Issue by AlexAegis** [ostwilkens/bevy_web_fullscreen#7]
Nice plugin, works great!

Do you plan to release it on cargo?

**Comment by bakcxoj** [comment]
Also interested in this

**Comment by ostwilkens** [comment]
Thank you for the interest! 
I am looking into it. It will be a good first crate for me.

**Comment by TotalKrill** [comment]
Came here to ask for the same thing, it really is not a big deal to publish to crates.io. 

Basically just use "cargo publish", and fix the required fields in the Cargo.toml (cargo publish will tell you the missing ones)

**Comment by ostwilkens** [comment]
> Came here to ask for the same thing, it really is not a big deal to publish to crates.io. 
> 
> 
> 
> Basically just use "cargo publish", and fix the required fields in the Cargo.toml (cargo publish will tell you the missing ones)

The thing that has been stopping me is that I need to decide on how to version it. Decision paralysis! Should the version match bevy, or not? I'm open to suggestions.

**Comment by AlexAegis** [comment]
Let openGPT decide ;)

**Comment by AlexAegis** [comment]
To be serious Bevy isn't 1.0 yet and likely wont be for a while. Also this is a tiny plugin and I don't think you'd like to come back to it just to bump versions every time bevy releases a new one even if there is no breaking change to it.

I'd say release it as 0.1 or something similar and let it be. If something breaks, people will raise an issue/PR. I wouldn't even lock it to a specific bevy version.

Also, bevy could just make this plugin obsolete by incorporating the functionality at any release. So don't overthink it.

**Comment by AlexAegis** [comment]
(Sorry for the spam)

I'd discourage publishing manually though. Let github take care of it, I have a tiny rust lib too and this is what I use to release it (I just updated it to be more inline with my other ci scripts, action based gh pages, and some conditionals on release/docs jobs):

https://github.com/AlexAegis/cpt/blob/master/.github/workflows/ci.yml

And you can get a token here: https://crates.io/settings/tokens

And turn on action based pages here: https://github.com/ostwilkens/bevy_web_fullscreen/settings/pages

**Comment by TotalKrill** [comment]
> > Came here to ask for the same thing, it really is not a big deal to publish to crates.io.
> > Basically just use "cargo publish", and fix the required fields in the Cargo.toml (cargo publish will tell you the missing ones)
> 
> The thing that has been stopping me is that I need to decide on how to version it. Decision paralysis! Should the version match bevy, or not? I'm open to suggestions.

In the case of this highly specific plugin, I would say match bevy versions,reason being that I cannot see any additional features making it into this crate, if that is true, then versioning could as well join bevy. 

For other crates, where a larger functionality or modifiable component is being added, I would say not to limit oneself, but instead keep a table with version compatiblity in the README.md

**Comment by ostwilkens** [comment]
Thank you for the replies! I went with minimum effort for now, and simply published the existing version. 
https://crates.io/crates/bevy_web_fullscreen
